name: Jekyll Deploy Page

on:
  push:
    branches: [ main ]

jobs:
  jekyll_deploy:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v4

    - name: Build ğŸ—ï¸ with Jekyll 4
      uses: jerryjvl/jekyll-build-action@v1
      
    - name: Deploy ğŸš€ to GitHub Pages Branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        cname: cevi.tools
